### ISSUE TITLE
System.ArgumentOutOfRangeException when using the Export.bat

### ISSUE THREAD

**Issue by Shokupanda** [pleonex/PokemonConquest#1]
As the title suggests, I get a System.ArgumentOutOfRangeException when using the Export.bat.
I still get a "text" folder, but when I use the import.bat it'll give me an error too, so I guess this one causes trouble in the first place.

![error](https://user-images.githubusercontent.com/23729870/59676241-6b866500-91c7-11e9-8c17-765108b35465.png)

**Comment by pleonex** [comment]
This tool is deprecated. I am working in the new ones (the actual problem is that it was only tested with the Jap version and the EU version has some 0 byte files).
