### ISSUE TITLE
Error when running build.ps1

### ISSUE THREAD

**Issue by Shokupanda** [pleonex/PokemonConquest#3]
Hi, there! I was excited to see you're working on the Pokémon Conquest tools, so I gave it a try right away. Unfortunately it gives me an error when running build.ps1.

I put the ROM file in the "GameData\root" folder and overlay9_10 and overlay9_11 in the "GameData\root\system" folder.

This is what I get:
![error](https://user-images.githubusercontent.com/23729870/61999736-e183c300-b0c7-11e9-81aa-7a1ca849d589.png)

It says "An attempt was made to read beyond the end of the data stream."
I hope you can help! Thanks in advance!

**Comment by pleonex** [comment]
Yeah, I am still working on it so I didn't implement the decompression algorithm and it's still a manual process. For now, you would need to decompress the overlay files with `blz.exe -d overlay9_X` (you can get the tools from here: https://www.romhacking.net/utilities/826/)

**Comment by Shokupanda** [comment]
Hey, thank you for the fast reponse!

I did as you said and now the Export-Font works fine! But I just ran into the next error:
![error](https://user-images.githubusercontent.com/23729870/62013978-3c3a1f00-b19b-11e9-9040-e1c4a7a28939.png)
"The object reference was not set to an object instance."

**Comment by pleonex** [comment]
The tool doesn't read yet the rom file directly. You need to extract the
data folder of the ROM into root/rom. So the script can find the files at
GameData/root/rom/data/Building.dat for instance.

Le lun. 29 juil. 2019 à 00:54, Shokupanda <notifications@github.com> a
écrit :

**Comment by pleonex** [comment]
Thanks 😄 
Right now we could import the secondary texts, that is, the .po files that are not inside the _messages_ folder. It's missing just the Cake script file but the code and test are already working. For the .po files in the _messages_ folder, I need still to implement the code to import.

**Comment by Shokupanda** [comment]
Hey, I just tested your import feature and it works JUST GREAT! It even gets the umlauts correct right away! I was scared it would give me errors when using umlauts but it works perfectly!! I was already able to translate the secondary texts via hex editor in Tinke, but that way it's a bit easier. Espescially if I like to re-do some of my translations. :smile:

One thing I'm wondering about, though... why didn't you include the Pokemon.dat in the exporter/importer.cake? They can be translated too! In German, French and Spanish the Pokémon have different names! :smiley: 

Can't wait for the "messages" importer, since that's the only thing missing for my translation patch! =D
Thank you so much for all the work you put into this. Without your tools I wouldn't even have been able to start this project!

**Comment by pleonex** [comment]
Thanks :smile: 

I was also surprise to see that the game font includes the characters for many European languages.
![regular](https://user-images.githubusercontent.com/3107481/62292206-2a3fd100-b466-11e9-9f80-b771ee840dd7.png)

And I didn't know that in German and French the name of the Pokemon are translated. That is not the case for Spanish, where we use the English name always. In any case, I have just added support for the `Pokemon.dat` file. The import for the messages files may take a bit more time since it's more complex due to the control codes.

**Comment by Shokupanda** [comment]
Ooooh, right, the Pokémon names were only translated in German and French. I thought it was Spanish too, but you're right, Spanish and Italian used the English names! Thanks for adding the Pokemon.dat! :smiley: 

Alright, I'll wait paitently for the message importer, then. :-) I'm not done with all the dialogue text anyways, so there's still stuff for me to do. Keep up the good work!! ^_^

**Comment by pleonex** [comment]
Thanks. Then I will close this issue since it's working that part now.
