### ISSUE TITLE
Error with importer.cake

### ISSUE THREAD

**Issue by Shokupanda** [pleonex/PokemonConquest#4]
Sorry, for bothering you with another error. I really tried to find out what's the cause of the problem, but just couldn't get behind it.

Before the "Pokemon.dat" was implemented, the importer.cake worked fine for me. Now that it's implemented I get this error again:

![error](https://user-images.githubusercontent.com/23729870/63019055-a4c31480-be9a-11e9-90bd-9556c0f164ba.png)

I don't know what's the cause. In the GameData folder I have the "extracted", "output", "root" and "translated" folders. In The "root" folder there's the rom file and the "rom/data" folder which has all the .dat files... so I really don't get what's missing for the script to work?

I hope you can help! Thank you so much in advance!

**Comment by pleonex** [comment]
No problem! That's the reason why we have this GitHub issues :)

Can you run the scripts adding the argument `-verbosity diagnostic` paste the full output here?

**Comment by Shokupanda** [comment]
Okay! This is the output:

`An error occurred when executing task 'Import-TextLists'.
Error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.NullReferenceException: Der Objektv
erweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Submission#0.<>c.<<Initialize>>b__0_2(BuildData data)
   bei Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   bei Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   bei Submission#0.<<Initialize>>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   bei Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   bei Cake.Commands.BuildCommand.Execute(CakeOptions options)
   bei Cake.CakeApplication.Run(CakeOptions options)
   bei Cake.Program.Main()
---> (Interne Ausnahme #0) System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgeleg
t.
   bei Submission#0.<>c.<<Initialize>>b__0_2(BuildData data)
   bei Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   bei Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   bei Submission#0.<<Initialize>>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---`

**Comment by pleonex** [comment]
Can you double check that in your folder `GameData/root/data/` you have the file `Pokemon.dat`?

**Comment by Shokupanda** [comment]
Wait, there's supposed to be a "GameData/root/data" folder? I thought it's "GameData/root/rom/data". But I copied the whole data folder in the "GameData/root", run the script and it gave me the same result...

And yup, it's there!
![pokemondat](https://user-images.githubusercontent.com/23729870/63025493-97f9ed00-bea9-11e9-9652-41a16b71f782.png)

**Comment by pleonex** [comment]
Sorry for the delay. I think I have fixed the problem. It was failing only on Windows (sometimes I use Linux) because of the path. It should be fixed now.

**Comment by Shokupanda** [comment]
Hey, no problem! I tried it right away and now it works perfectly! Thank you very much!! :smiley:
